/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      screens: {
        '2xl': '1440px',
        'lg-nav': '990px',
        'md-tab': '768px',
        'sm-tab': '755px',
        'xl-tab': '1125px',
      },
      fontSize: {
        'h1': ['24px', { lineHeight: '1.2', fontWeight: '700'}],
        'md-h1': ['26px', { lineHeight: '1.2', fontWeight: '700'}],
        'lg-h1': ['27px', { lineHeight: '1.2', fontWeight: '700'}],
        '2xl-h1': ['28px', { lineHeight: '1.2', fontWeight: '700'}],

        'h2': ['22px', { lineHeight: '1.3', fontWeight: '700'}],
        'md-h2': ['24px', { lineHeight: '1.3', fontWeight: '700'}],
        'lg-h2': ['25px', { lineHeight: '1.3', fontWeight: '700'}],
        '2xl-h2': ['26px', { lineHeight: '1.3', fontWeight: '700'}],

        'h3': ['20px', { lineHeight: '1.3', fontWeight: '600'}],
        'md-h3': ['22px', { lineHeight: '1.3', fontWeight: '600'}],
        'lg-h3': ['23px', { lineHeight: '1.3', fontWeight: '600'}],
        '2xl-h3': ['24px', { lineHeight: '1.3', fontWeight: '600'}],

        'h4': ['15px', { lineHeight: '1.3', fontWeight: '600'}],
        'md-h4': ['16px', { lineHeight: '1.3', fontWeight: '600'}],
        'lg-h4': ['17px', { lineHeight: '1.3', fontWeight: '600'}],
        '2xl-h4': ['18px', { lineHeight: '1.3', fontWeight: '600'}],

        'card-header': ['18px', { lineHeight: '1.5', fontWeight: '700'}],
        'md-card-header': ['20px', { lineHeight: '1.5', fontWeight: '700'}],
        'lg-card-header': ['21px', { lineHeight: '1.5', fontWeight: '700'}],
        '2xl-card-header': ['22px', { lineHeight: '1.5', fontWeight: '700'}],

        'paragraph': ['15px', { lineHeight: '1.6', fontWeight: '300'}],
        'md-paragraph': ['16px', { lineHeight: '1.6', fontWeight: '300'}],
        'lg-paragraph': ['17px', { lineHeight: '1.6', fontWeight: '300'}],
        '2xl-paragraph': ['18px', { lineHeight: '1.6', fontWeight: '300'}],

        'paragraph-m': ['15px', { lineHeight: '1.5', fontWeight: '500'}],
        'md-paragraph-m': ['16px', { lineHeight: '1.5', fontWeight: '500'}],
        'lg-paragraph-m': ['17px', { lineHeight: '1.5', fontWeight: '500'}],
        '2xl-paragraph-m': ['18px', { lineHeight: '1.5', fontWeight: '500'}],

        'tooltip': ['12px', { lineHeight: '1.6', fontWeight: '400'}],
        'md-tooltip': ['13px', { lineHeight: '1.6', fontWeight: '400'}],
        'lg-tooltip': ['14px', { lineHeight: '1.6', fontWeight: '400'}],
        '2xl-tooltip': ['15px', { lineHeight: '1.6', fontWeight: '400'}],
      },
      fontFamily: {
        poppins: ['Poppins', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
      },
      colors: {
        'light-bg-white': '#FFFFFF',
        'light-bg-primary': '#F8F9FA',
        'light-bg-secondary': '#E9ECEF',
        'light-card': '#FFFFFF',
        'accent-primary': '#1A73E8',
        'accent-primary-dark': '#145CBF',
        'accent-secondary': '#8A2BE2',
        'accent-secondary-dark': '#6A1BC0',
        'text-dark': '#212529',
        'text-muted': '#6C757D',
        'border-color': '#DEE2E6',
        'neutral-700': '#4A5568',

        'btn-github-light': '#212529',
        'btn-github-light-text': '#FFFFFF',
        'btn-github-dark-text': '#121212',

        'btn-video-light': '#20C997',
        'btn-video-light-hover': '#17A2B8',
        'btn-video-light-text': '#FFFFFF',
        
        'btn-presentation-light': '#6F42C1',
        'btn-presentation-light-hover': '#563D7C',
        'btn-presentation-light-text': '#FFFFFF',
        dark: {
          'bg-primary': '#121212',
          'bg-secondary': '#1E1E1E',
          'card': '#2D2D2D',
          'bg-navbar-dark': '#3A3A3A',
          'accent-primary': '#63B3ED',
          'accent-primary-dark': '#4299E1',
          'accent-secondary': '#BB86FC',
          'accent-secondary-dark': '#9A67EA',
          'text-dark': '#E0E0E0',
          'text-muted': '#A0A0A0',
          'border-color': '#424242',
          'neutral-700': '#CBD5E0',

          'btn-github-dark': '#E0E0E0',
          'btn-github-dark-hover': '#CED4DA',

          'btn-video-dark': '#48D1CC',
          'btn-video-dark-hover': '#20B2AA',
          'btn-video-dark-text': '#121212',

          'btn-presentation-dark': '#9370DB',
          'btn-presentation-dark-hover': '#7B68EE',
          'btn-presentation-dark-text': '#121212',
        },
      },
      spacing: {
        'header-content': '40px',
        'tag-gap': '20px',
        'section-gap': '90px',
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic':
          'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
      keyframes: {
        bounceIn: {
          '0%': { opacity: '0', transform: 'translateY(20px) scale(0.8)' },
          '60%': { opacity: '1', transform: 'translateY(-5px) scale(1.05)' },
          '100%': { transform: 'translateY(0) scale(1)' },
        },
        spinCustom: {
          from: { transform: 'rotate(0deg)' },
          to: { transform: 'rotate(360deg)' },
        },
        expandFade: {
          '0%': { transform: 'scale(0.7)', opacity: '0.8' },
          '50%': { transform: 'scale(1.1)', opacity: '0.4' },
          '100%': { transform: 'scale(0.7)', opacity: '0.8' },
        },
        popOut: {
          '0%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.1)' },
          '100%': { transform: 'scale(1)' },
        },
        bounceFade: {
          '0%, 100%': { transform: 'translateY(0)', opacity: '1' },
          '50%': { transform: 'translateY(10px)', opacity: '0.7' },
        },
        fadeIn: {
          from: { opacity: '0', transform: 'translateY(20px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        glow: {
          '0%, 100%': { boxShadow: '0 0 0 0 rgba(0, 123, 255, 0.7)' },
          '50%': { boxShadow: '0 0 15px 5px rgba(0, 123, 255, 0.3)' },
        },
        tooltipAppear: {
          from: { opacity: '0', transform: 'translate(-50%, 10px) scale(0.95)' },
          to: { opacity: '1', transform: 'translate(-50%, 0) scale(1)' },
        },
        moveHorizontal: {
          '0%': { transform: 'translateX(0)' },
          '50%': { transform: 'translateX(50px)' },
          '100%': { transform: 'translateX(0)' },
        },
        blob: {
          '0%': { transform: 'translate(0, 0) scale(1)' },
          '25%': { transform: 'translate(var(--blob-x1, 20px), var(--blob-y1, -30px)) scale(1.1)' },
          '50%': { transform: 'translate(var(--blob-x2, -15px), var(--blob-y2, 20px)) scale(0.9)' },
          '75%': { transform: 'translate(var(--blob-x3, 30px), var(--blob-y3, -10px)) scale(1.05)' },
          '100%': { transform: 'translate(0, 0) scale(1)' },
        },
        float: {
          '0%': { transform: 'translate(0, 0) rotate(0deg)' },
          '25%': { transform: 'translate(var(--float-x1, 15px), var(--float-y1, -25px)) rotate(var(--float-deg1, 10deg))' },
          '50%': { transform: 'translate(var(--float-x2, -10px), var(--float-y2, 15px)) rotate(var(--float-deg2, -5deg))' },
          '75%': { transform: 'translate(var(--float-x3, 20px), var(--float-y3, -5px)) rotate(var(--float-deg3, 15deg))' },
          '100%': { transform: 'translate(0, 0) rotate(0deg)' },
        },
        floatReverse: {
          '0%': { transform: 'translate(0, 0) rotate(0deg)' },
          '25%': { transform: 'translate(var(--float-rev-x1, -15px), var(--float-rev-y1, 25px)) rotate(var(--float-rev-deg1, -10deg))' },
          '50%': { transform: 'translate(var(--float-rev-x2, 10px), var(--float-rev-y2, -15px)) rotate(var(--float-rev-deg2, 5deg))' },
          '75%': { transform: 'translate(var(--float-rev-x3, -20px), var(--float-rev-y3, 5px)) rotate(var(--float-rev-deg3, -15deg))' },
          '100%': { transform: 'translate(0, 0) rotate(0deg)' },
        },
        floatSubtle: {
          '0%, 100%': { transform: 'translateY(0) translateX(0)' },
          '50%': { transform: 'translateY(var(--float-subtle-y, -10px)) translateX(var(--float-subtle-x, 5px))' },
        },
        floatSubtleReverse: {
          '0%, 100%': { transform: 'translateY(0) translateX(0)' },
          '50%': { transform: 'translateY(var(--float-subtle-rev-y, 10px)) translateX(var(--float-subtle-rev-x, -5px))' },
        },
        spinFast: {
          from: { transform: 'rotate(0deg)' },
          to: { transform: 'rotate(360deg)' },
        },
        spinVerySlow: {
          from: { transform: 'rotate(0deg)' },
          to: { transform: 'rotate(360deg)' },
        },
        spinSlow: {
          from: { transform: 'rotate(0deg)' },
          to: { transform: 'rotate(360deg)' },
        },
        cursorPulse: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.2' },
        },
        wordFlash: {
          '0%': { backgroundColor: 'rgba(26, 115, 232, 0.1)' },
          '100%': { backgroundColor: 'transparent' },
        },
        shakeX: {
          '0%, 100%': { transform: 'translateX(0)' },
          '10%, 30%, 50%, 70%, 90%': { transform: 'translateX(-5px)' },
          '20%, 40%, 60%, 80%': { transform: 'translateX(5px)' },
        },
        shakeY: {
          '0%, 100%': { transform: 'translateY(0)' },
          '10%, 30%, 50%, 70%, 90%': { transform: 'translateY(-5px)' },
          '20%, 40%, 60%, 80%': { transform: 'translateY(5px)' },
        },
        pulseLight: {
          '0%, 100%': { boxShadow: '0 0 0 0 rgba(106, 62, 250, 0.4)' },
          '50%': { boxShadow: '0 0 0 8px rgba(106, 62, 250, 0)' },
        },
        pulseDark: {
          '0%, 100%': { boxShadow: '0 0 0 0 rgba(138, 92, 255, 0.4)' },
          '50%': { boxShadow: '0 0 0 8px rgba(138, 92, 255, 0)' },
        },
        bounceError: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-15px)' },
        },
        fadeInOut: {
          '0%': { opacity: '0' },
          '50%': { opacity: '1' },
          '100%': { opacity: '0' },
        },
        floatError: {
          '0%': { transform: 'translate(10px, -10px) scale(1.05)' },
          '25%': { transform: 'translate(0, 0) scale(1)' },
          '50%': { transform: 'translate(-5px, 5px) scale(0.95)' },
          '75%': { transform: 'translate(8px, -8px) scale(1.02)' },
          '100%': { transform: 'translate(10px, -10px) scale(1.05)' },
        },
        dotPulse: {
          '0%, 100%': { transform: 'translateY(0)', opacity: '1' },
          '50%': { transform: 'translateY(-4px)', opacity: '0.6' },
        },
        wavyDot: {
          '0%, 100%': { transform: 'translateX(0) translateY(0)', opacity: '1' },
          '25%': { transform: 'translateX(2px) translateY(-2px)', opacity: '0.8' },
          '50%': { transform: 'translateX(0) translateY(0)', opacity: '1' },
          '75%': { transform: 'translateX(-2px) translateY(2px)', opacity: '0.8' },
        },
        textBump: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-2px)' },
        },
        slideInUpFade: {
          '0%': { opacity: '0', transform: 'translate(-50%, 10px) scale(0.9)' },
          '100%': { opacity: '1', transform: 'translate(-50%, 0) scale(1)' },
        },
        slideOutDownFade: {
          '0%': { opacity: '1', transform: 'translate(-50%, 0) scale(1)' },
          '100%': { opacity: '0', transform: 'translate(-50%, 10px) scale(0.9)' },
        },
        slideInUpFadeWithBump: {
          '0%': { opacity: '0', transform: 'translate(-50%, 10px)' },
          '75%': { opacity: '1', transform: 'translate(-50%, -2px)' },
          '100%': { opacity: '1', transform: 'translate(-50%, 0)' },
        },
        pulseSubtle: {
          '0%, 100%': { boxShadow: '0 0 0 0 rgba(26, 115, 232, 0.4)' },
          '50%': { boxShadow: '0 0 20px 10px rgba(26, 115, 232, 0)' },
        },
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        pulseStrong: {
          '0%, 100%': { boxShadow: '0 0 0 0 rgba(26, 115, 232, 0.6)' },
          '50%': { boxShadow: '0 0 30px 15px rgba(26, 115, 232, 0)' },
        },
      },
      animation: {
        'bounce-in': 'bounceIn 0.4s ease-out forwards',
        'spin-custom': 'spinCustom 1s linear infinite',
        'spin-fast': 'spinFast 5s linear infinite',
        'spin-very-slow': 'spinVerySlow 30s linear infinite',
        'expand-fade': 'expandFade 2s ease-in-out infinite',
        'pop-out': 'popOut 0.3s ease-out',
        'bounce-fade': 'bounceFade 1.5s infinite ease-in-out',
        'fade-in': 'fadeIn 0.5s ease-out forwards',
        'glow': 'glow 2s infinite',
        'tooltip-appear': 'tooltipAppear 0.2s ease-out forwards',
        'move-horizontal': 'moveHorizontal 15s infinite ease-in-out alternate',
        'move-horizontal-reverse': 'moveHorizontal 15s infinite ease-in-out alternate-reverse',
        'blob-1': 'blob 8s infinite ease-in-out alternate var(--blob-delay-1, 0s)',
        'blob-2': 'blob 10s infinite ease-in-out alternate var(--blob-delay-2, 0s)',
        'blob-3': 'blob 9s infinite ease-in-out alternate var(--blob-delay-3, 0s)',
        'float': 'float 10s infinite ease-in-out alternate',
        'float-reverse': 'floatReverse 12s infinite ease-in-out alternate',
        'float-slow': 'float 15s infinite ease-in-out alternate',
        'float-fast': 'float 8s infinite ease-in-out alternate',
        'float-subtle': 'floatSubtle 8s infinite ease-in-out alternate',
        'float-subtle-reverse': 'floatSubtleReverse 9s infinite ease-in-out alternate',
        'spin-slow': 'spinSlow 20s linear infinite',
        'spin-slow-reverse': 'spinSlow 20s linear infinite reverse',
        'cursor-pulse': 'cursorPulse 1s infinite steps(1)',
        'word-flash': 'wordFlash 0.3s ease-out forwards',
        'shake': 'shakeX 0.5s ease-in-out',
        'shake-x': 'shakeX 0.5s ease-in-out',
        'shake-y': 'shakeY 0.5s ease-in-out',
        'pulse-light': 'pulseLight 1.5s infinite',
        'pulse-dark': 'pulseDark 1.5s infinite',
        'bounce-error': 'bounceError 1.5s infinite ease-in-out',
        'fade-in-out': 'fadeInOut 2s infinite ease-in-out',
        'float-error': 'floatError 12s infinite ease-in-out alternate',
        'dot-pulse-1': 'dotPulse 1.2s infinite ease-in-out',
        'dot-pulse-2': 'dotPulse 1.2s infinite ease-in-out 0.6s',
        'wavy-dot-1': 'wavyDot 2s infinite ease-in-out',
        'wavy-dot-2': 'wavyDot 2s infinite ease-in-out 0.5s',
        'text-bump': 'textBump 1.5s infinite ease-in-out',
        'slide-in-up-fade': 'slideInUpFade 0.3s ease-out forwards',
        'slide-out-down-fade': 'slideOutDownFade 0.3s ease-out forwards',
        'animate-slide-in-up-fade-with-bump': 'slideInUpFadeWithBump 0.5s ease-out forwards',
        'pulse-strong': 'pulseStrong 2s infinite ease-in-out',
        'fade-in-up': 'fadeInUp 0.6s ease-out forwards',
      },
      animationDelay: {
        '100': '100ms',
        '200': '200ms',
        '300': '300ms',
        '400': '400ms',
        '500': '500ms',
        '600': '600ms',
        '700': '700ms',
        '800': '800ms',
        '900': '900ms',
        '1000': '1000ms',
        '1500': '1500ms',
        '2000': '2000ms',
        '2500': '2500ms',
        '3000': '3000ms',
        '3500': '3500ms',
        '4000': '4000ms',
        '4500': '4500ms',
        '5000': '5000ms',
        '5500': '5500ms',
        '6000': '6000ms',
        '6500': '6500ms',
        '7000': '7000ms',
        '7500': '7500ms',
        '8000': '8000ms',
        '8500': '8500ms',
        '9000': '9000ms',
        '9500': '9500ms',
        '10000': '10000ms',
        '10500': '10500ms',
        '11000': '11000ms',
        '11500': '11500ms',
        '12000': '12000ms',
        '12500': '12500ms',
        '13000': '13000ms',
        '13500': '13500ms',
        '14000': '14000ms',
        'blob-delay-1': '0s',
        'blob-delay-2': '2s',
        'blob-delay-3': '4s',
        'blob-delay-4': '6s',
      }
    },
  },
  plugins: [],
};